INSERT INTO lanterns (id, name, role, msg, created_at) VALUES
  ('seed-cindy',
   'Cindy Wu',
   'Mother',
   'Message goes here',
   datetime('now', '-14 hours')),
  ('seed-peter',
   'Peter Wu',
   'Father',
   'Message goes here',
   datetime('now', '-74 hours')),
  ('seed-laura',
   'Laura Tan',
   'Aunt',
   'Message goes here',
   datetime('now', '-74 hours')),
  ('seed-brian',
   'Brian Tan',
   'Uncle',
   'Message goes here',
   datetime('now', '-74 hours'));
